### ISSUE TITLE
Consider using a hardware-specific license, like the CERN Open Hardware License

### ISSUE THREAD

**Issue by DeflateAwning** [dj505/RP2040-Zero-KiCAD#2]
Consider using a hardware-specific license for this project (and others), like the [CERN Open Hardware Licence Version 2 - Permissive
](https://choosealicense.com/licenses/cern-ohl-p-2.0/).

The MIT License (currently used for this project) doesn't really cover hardware designs like this. While the intention is clear, it prevents certain groups/organizations from using it.

**Comment by dj505** [comment]
Very good to know, thank you! I will look into updating the license when I'm home from work.

**Comment by holly-hacker** [comment]
Hi, have you been able to look into this?

**Comment by dj505** [comment]
Hey, apologoes for keeping you guys waiting! It completely slipped my mind when this issue was first posted. I've moved the project to the CERN Open Hardware License that @DeflateAwning initially suggested since it matches what I intended for this repo!
